# Generated by Django 4.1.3 on 2023-01-09 18:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='pub_date',
            field=models.DateTimeField(default=datetime.date(2023, 1, 9), verbose_name='дата публикации'),
        ),
    ]
