# Generated by Django 4.1.7 on 2023-03-05 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_machine', models.TextField(max_length=100, verbose_name='Машина')),
                ('description', models.TextField(verbose_name='Пояснение')),
            ],
            options={
                'verbose_name': 'Машина',
                'verbose_name_plural': 'Машины',
            },
        ),
        migrations.CreateModel(
            name='React',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.CharField(max_length=30)),
                ('department', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_work', models.CharField(max_length=100, verbose_name='Работа')),
            ],
            options={
                'verbose_name': 'Работа',
                'verbose_name_plural': 'Работы',
            },
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_stage', models.CharField(max_length=100, verbose_name='Этап')),
                ('work_id', models.PositiveIntegerField(verbose_name='Job')),
                ('execution_time', models.PositiveIntegerField(verbose_name='Время выполнения')),
                ('priority', models.PositiveIntegerField(verbose_name='Приоритет выполнения')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.machine', verbose_name='Машина')),
            ],
            options={
                'verbose_name': 'Этап',
                'verbose_name_plural': 'Этапы',
            },
        ),
    ]
