# Generated by Django 4.1.7 on 2023-03-12 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='due_dates',
            field=models.PositiveIntegerField(default=0, verbose_name='Due dates'),
        ),
        migrations.AddField(
            model_name='work',
            name='release_dates',
            field=models.PositiveIntegerField(default=0, verbose_name='Release dates'),
        ),
    ]
